### ISSUE TITLE
Item position when building dynamic menu via listeners

### ISSUE THREAD

**Issue by benjamindulau** [KnpLabs/KnpMenu#112]
It is actually impossible to order items exactly as we'd like to when menu are built by using event system.

We are building a complex admin in which each module has to hook into the menus in order to add its own menu items. To do so, the core module dispatches an event and each module implements its own event listener to get a chance to add its menu items in the existing menus.

The actual `moveToPosition()` method moves the item in real time, which makes it useless in an event driven menu system.

Would you consider adding a simple `position` attribute which could be used at rendering time ? If you have any idea about how it could easily implemented, I'd be glad to make a PR ;-)

Thanks.

**Comment by TomasVotruba** [comment]
@benjamindulau @khal3d What works for me is simply settings priority to EventSubscriber.
