### ISSUE TITLE
Voter for tree structured menu

### ISSUE THREAD

**Issue by sagikazarmark** [KnpLabs/KnpMenu#173]
When it comes to tree hierarchy we usually see uris like this:
`tree-root/child1/grandchild1`. I was thinking about a Voter which checks this hierarchy, so parent items can also be "current". In the example Root item, Child 1 item and Grandchild item is current no matter we are at Grandchild 1 page.

What do you think?

**Comment by dbu** [comment]
we have the isAncestor check these days. is this issue still relevant?
