### ISSUE TITLE
Rename FactoryInterface and ItemInterface

### ISSUE THREAD

**Issue by afurculita** [KnpLabs/KnpMenu#190]
ItemInterface defines the interface for a menu item, so it should be named MenuItemInterface. FactoryInterface creates objects of type ItemInterface, that are menu items, so it should be named MenuFactoryInterface. 

Even if you have in namespace \Menu\, "Menu" has to be present in the class interface name too.

**Comment by stof** [comment]
Renaming interface is a BC break. It is not worth it IMO. Thus, I don't think duplicating Menu in the interface short name (the interface name is ``Knp\Menu\ItemInterface``, not ``ItemInterface``)
