### ISSUE TITLE
ISO-8859 problem with displaying menu

### ISSUE THREAD

**Issue by yourithielen** [KnpLabs/KnpMenu#191]
When a menu is defined in a file that is ISO-8859 and characters with accents are used the item in the output HTML is empty. When this file is converted to UTF-8 it is displayed.

Is UTF-8 a requirement?

**Comment by folliked** [comment]
Hello,

No, you can configure Silex or Symfony (if you use it, you must specify the charset), also you can specify the charset in the renderer of KnpMenu. A piece of doc is missing about that. 

If you use the list renderer:

```php
$your renderer = new \Knp\Menu\Renderer\ListRenderer($itemMatcher, $someOptionsOrNot, "ISO-8859-1");
```

or  if you use the twig renderer:
```php
$twig = new \Twig_Environment($twigLoader, array('charset' => 'ISO-8859-1'));
```

*NB: you say "ISO-8859" it doesn't exist but you think probably "ISO-8859-1"?*

PS: for that i convert the files php and twig of my project to  'ISO-8859-1' and i read the following docs:

- http://twig.sensiolabs.org/doc/api.html
- http://silex.sensiolabs.org/doc/services.html
