### ISSUE TITLE
Generate custom menu view

### ISSUE THREAD

**Issue by maniaf69** [KnpLabs/KnpMenu#192]
hi 
How do you like menu out of it and append class to sub ul?
```html
<ul class="root">
	<li class="child">Link1
		<ul class="submenu">
			<li>sub link 1</li>
		</ul>
	</li>
</ul>
```

**Comment by maniaf69** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/5269966/6106501/3571a7d0-b077-11e4-8c41-8be2d01374e2.jpg)

**Comment by stof** [comment]
this is what ``childrenAttributes`` are about (they are attributes for the list of children): https://github.com/KnpLabs/KnpMenu/blob/master/doc/01-Basic-Menus.markdown#menu-attributes
