### ISSUE TITLE
League Container as provider

### ISSUE THREAD

**Issue by sagikazarmark** [KnpLabs/KnpMenu#195]
Would you accept a PR containing providers using [league/container](http://container.thephpleague.com/)?

**Comment by stof** [comment]
Well, the drawback of putting integrations in KnpMenu directly is that it makes it a pain to handle the versionning of the other project.
For instance, I have no idea how I will support Silex 2.0 (and Pimple 3.0). There would be 2 solutions if it stays in the KnpMenu repo itself, none of them being good:

- create a separate Silex2 ServiceProvider alongside the existing one, and letting people choose the right one based on their version of Silex
- break BC by migration the service provider to Silex2 (and dropping the support of Silex 1), which would force to bump the major version of KnpMenu just for that, while it is related to an integration to a third-party package.

As far as dependency management is concerned, keeping such integrations in separate packages works better (but it force the user to depend on this extra package though)

**Comment by sagikazarmark** [comment]
I see. My problem with moving every integrations into separate package is that you have to setup it under a separate vendor, namespace, etc.

What if I create a package (under a custom composer vendor) and put everything under `Knp\Menu` namespace? Is that a violation of any kind of rules?

Also, what should I call it? league-container-knp-menu-container-integration?

Any place to "collect" such third-party integrations?

**Comment by stof** [comment]
Well, I'm quite sure using the ``Knp`` namespace for your own library would be considered a violation by the KnpLabs guys (but this is my own guess given that I'm not working for KnpLabs anymore since years).

Regarding the integration, I guess using the wiki of the repo might work (as done for [Silex](https://github.com/silexphp/Silex/wiki/Third-Party-ServiceProviders) for instance). What do you think ?

**Comment by sagikazarmark** [comment]
Could work. And given the names on the linked wiki, `knp-menu-league-container-integration` is not a bad name at all. ;)

**Comment by sagikazarmark** [comment]
Here it is:
https://github.com/indigophp/knp-menu-extensions

**Comment by stof** [comment]
@sagikazarmark I created the wiki page, so you can add you extension in the list: https://github.com/KnpLabs/KnpMenu/wiki/Extensions

I'm closing this issue
