### ISSUE TITLE
What is missing for 2.1?

### ISSUE THREAD

**Issue by WouterJ** [KnpLabs/KnpMenu#198]
Hello!

The CMF project is working hard towards a new release, including support for KnpMenu(Bundle) 2. However, we missed lots of templating functions which were added by #189. This one is not yet included in a release and will be included in the 2.1 release. (https://github.com/KnpLabs/KnpMenuBundle/pull/251 needs to be merged as well)

We wonder if there is anything we can help with to make the 2.1 release a thing. Can you maybe create a list of issues/PRs that should be finished/fixed before you think a 2.1 release is ready? This way, we can help you preparing the release, as it's currently a big blocker for the next CMF release (releasing without KnpMenu 2 support isn't a option because of Sonata).

/cc @dbu @lsmith77

**Comment by lsmith77** [comment]
or if there are no resources to maintain it .. the CMF project could maybe take over ..

**Comment by lsmith77** [comment]
ping @stof @Nek-

**Comment by Nek-** [comment]
@lsmith77 @WouterJ I'm going to check everything to prepare 2.1 this weekend. Sorry for not being active this last months: i'm not collaborator anymore.

Btw I will work with @Einenlum to release 2.1 asap.

**Comment by lsmith77** [comment]
w00t. great news

**Comment by lsmith77** [comment]
ping? :)

**Comment by Nek-** [comment]
Got back the rights on repo!

**Comment by lsmith77** [comment]
ok great .. did you also get access to KnpMenuBundle?

**Comment by lsmith77** [comment]
sorry .. I realize that in OSS priorities often need to be adjusted to work life .. but this is taking too long. I see one option is giving the CMF project release rights so that we can finish things up. Alternatively we will need to talk to @rande about potentially forking so that we can unblock our releases.

**Comment by rande** [comment]
@lsmith77 is KnpLabs not active anymore on the SF2 side ?

**Comment by lsmith77** [comment]
at least not very active anymore :-/

**Comment by docteurklein** [comment]
@rande @lsmith77 we only participate in things we use, and knpMenu is not in my toolbox usually :|
As always, finding extra time is the problem in this scenario.

But I think I can manage to get you write perms on the project, since it would be the best option for this repo's health.

**Comment by TomasVotruba** [comment]
@docteurklein :+1:

**Comment by lsmith77** [comment]
@docteurklein ok .. I guess it would be good to have @WouterJ have commit/release rights .. and maybe one more person from the CMF like @dbu or myself.

**Comment by lwagner** [comment]
OK @WouterJ , @dbu , and you @lsmith77 just got invited to the repo.

**Comment by lsmith77** [comment]
awesome!

**Comment by dbu** [comment]
> OK @WouterJ , @dbu , and you @lsmith77 just got invited to the repo.

thanks. is there someplace to coordinate with you to decide when to release
and similar questions? or shall we just coordinate on the cmf mailinglist?
