### ISSUE TITLE
When trying to use with Silex

### ISSUE THREAD

**Issue by misilot** [KnpLabs/KnpMenu#199]
Hi,

When trying to use with silex and following https://github.com/KnpLabs/KnpMenu/blob/master/doc/03-Silex-Integration.markdown

I get the followinge error:

```php
InvalidArgumentException in Container.php line 95: Identifier "autoloader" is not defined.
```
after adding
```php
$app['autoloader']->registerNamespace('Knp\Menu', __DIR__.'/vendor/KnpMenu/src');
```

If I skip that line, and just add
```php
$app->register(new \Knp\Menu\Integration\Silex\KnpMenuServiceProvider());
```
I get the followinge error:

```
ClassNotFoundException in KnpMenuServiceProvider.php line 18: Attempted to load interface "ServiceProviderInterface" from namespace "Silex".
Did you forget a "use" statement for "Pimple\ServiceProviderInterface"?
```

Thanks!

**Comment by Nek-** [comment]
Hello,

What is your version of Silex ?

**Comment by misilot** [comment]
"silex/silex": "~2.0@dev"; dev-master

**Comment by Nek-** [comment]
Hello, everything working on Silex 2 and 3 from here. (btw `~2.0@dev` is not the `dev-master`)

You don't need to register the lib by yourself: composer do it for you.

**Comment by misilot** [comment]
@Nek- 

I will try again tomorrow when I am in front of the code. 

So i won't need to do:

```php
$app->register(new \Knp\Menu\Integration\Silex\KnpMenuServiceProvider());
```

I was trying to use [these directions](https://github.com/KnpLabs/KnpMenu/blob/master/doc/03-Silex-Integration.markdown#registering-the-extension)

**Comment by Nek-** [comment]
You need to register KnpMenu inside Silex. But you don't need to register it inside autoloader if you're using composer.

**Comment by stof** [comment]
The service provider available in the library is for Silex 1, not for the dev version of Silex 2.

**Comment by johndodev** [comment]
Silex 2 has been released, is there a plan to provide a service provider ?
