### ISSUE TITLE
Could we add setter/getter for route and routeParameters?

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/KnpMenu#200]
Now to build link from route with parameters we use:
``` php
        $menu->addChild('Latest Blog Post', array(
            'route' => 'blog_show',
            'routeParameters' => array('id' => $blog->getId()),
        ));
```

We already had setter/getter for `uri` (`setUri` and `getUri`).
Could we also add setter/getter for route and parameters to set them by more convenient way with IDE's autocomplete like:
``` php
        $menu
            ->addChild('Latest Blog Post')
            ->setRoute('blog_show')
            ->setRouteParameters(array('id' => $blog->getId()));
        ;
        // or better
        $menu
            ->addChild('Latest Blog Post')
            ->setRoute('blog_show', array('id' => $blog->getId()))
        ;
```

Or this will broke BC?

**Comment by Nek-** [comment]
Theses options are defined by factories. We can't guess them. So no way to add getter and setters. We could do something with `__call` magic method, but it's still a problem for your IDE autocomplete :) .

Sorry !

**Comment by bocharsky-bw** [comment]
@Nek- I found solution in PR https://github.com/KnpLabs/KnpMenu/pull/203 . What do you think?
