### ISSUE TITLE
Failed to create a menu with 3 levels

### ISSUE THREAD

**Issue by danielnv18** [KnpLabs/KnpMenu#219]
Greetings Knp Community 

I'm trying to create a Menu with 3 levels in Symfony and I get this error
```Error: Call to a member function addChild() on null```

I'm creating a menu as a service following this [guide](http://symfony.com/doc/current/bundles/KnpMenuBundle/menu_service.html).

This is my menu builder
```php
// /src/AppBundle/Menu/MenuBuilder.php
$menu = $this->factory->createItem('root');

$menu->addChild('level1', ['uri' => '#']);

$menu['level1']->addChild('level2', ['uri' => '#' ]);

$menu['level2']->addChild('level3', ['uri' => '#' ]);

return $menu;
```
You can see all the files and config [here](https://gist.github.com/danielnv18/0b83fc81b1deb2089468)

The menu works good as long as I don't add a third menu level. I guess i'm doing something wrong but I'm not sure what. I did some search in google and all the examples are like [this](http://stackoverflow.com/a/11355455/2055057) and the example in the [documentation](https://github.com/KnpLabs/KnpMenu/blob/master/doc/01-Basic-Menus.markdown#working-with-your-menu-tree) is very similar.

This is some info in my composer.lock
KnpMenu Version
```json
"name": "knplabs/knp-menu",
"version": "v2.0.1",
"source": {
    "type": "git",
    "url": "https://github.com/KnpLabs/KnpMenu.git",
    "reference": "5758d0026d7ed00c8dd4727e413918cf2dc74c1a"
},
```
knp menu bundle
```json
"name": "knplabs/knp-menu-bundle",
"version": "v2.0.0",
"target-dir": "Knp/Bundle/MenuBundle",
"source": {
    "type": "git",
    "url": "https://github.com/KnpLabs/KnpMenuBundle.git",
    "reference": "bdfc95da5ff7e4e67f948aaa9ea5da835a3a9088"
},
```

Symfony version
```json
"name": "symfony/symfony",
"version": "v2.7.3",
"source": {
    "type": "git",
    "url": "https://github.com/symfony/symfony.git",
    "reference": "a9af4708b4bb650c4897e9b8dfbfbdb2ea5f0486"
},
```

Thanks in advantage

**Comment by WouterJ** [comment]
`level2` is a child of `level1`, but you try to retrieve it from `root`. The `root` menu only knows about a `level1` node, `level1` knows about the `level2` node. So you have to do `$menu['level1']['level2']->addChild(...)`. Please also note that `ItemInterface#addChild()` returns the added child, so you can change your code to something like this (which I find a bit prettier):

```php
$menu = $this->factory->createItem('root');

$menuLevel1 = $menu->addChild('level1', ['uri' => '#']);

$menuLevel2 = $menuLevel1->addChild('level2', ['uri' => '#' ]);

$menuLevel2->addChild('level3', ['uri' => '#' ]);
```

**Comment by danielnv18** [comment]
Thanks @WouterJ  for the support.

**Comment by WebToolsde** [comment]
I really don`t know why this menu works only like the way described by wouterj.

Why isn`t it possible to make it working like this?

      $this->menu->addChild('1');
      $parent=$this->menu->getChild(1);
      $parent->addChild('1.1');
      $parent=$this->menu->getChild(1.1);
      $parent->addChild('1.1.1');

I miss this feature.

**Comment by stof** [comment]
`1.1` is **not** a child of `$this->menu` in your case. That's why you cannot get it.

What you request would require making menu names unique in the whole menu tree, and making `getChild` traverse the whole tree (and its name would not be right anymore btw).

**Comment by WebToolsde** [comment]
You are right. Traversing the whole menu would be fine. Of course with the help of a unique ID. 

I miss something like getChildperID($id)

At the moment I label the child with setLabel because I can not work with ID`s only.

In several use cases menu names are not unique. This wouldn`t be practical. So if you have a shop there is a category "Shirts". And this can exist several times. Men Shirts / Woman Shirts / Kids Shirts.
So the only chance is to work with the setLabel function and using the name as "id".

**Comment by WebToolsde** [comment]
can you please show me how to add a menu point for level 3 or more?

**Comment by stof** [comment]
to add a menu item at level 3, you need to locate its parent (the level 2 node) and add a child in it. there is no other way. That's how tree manipulation works.

@wouterj's example relied on the fact that `addChild` returns the added item. It could also be replaced by first adding the child and then getting it from its parent separately, depending on the way your code is organized. But you cannot add a level 3 node directly from the root.
