### ISSUE TITLE
RegexVoter check current route instead of child route ?

### ISSUE THREAD

**Issue by Jerome1337** [KnpLabs/KnpMenu#227]
I have made a function to check childs routes with regexVoter

```
 private function matchingRoute($menu)
    {
        foreach ($menu->getChildren() as $child) {
            $childRegex = $child->getAttribute('regex');

            $voter = new RegexVoter($childRegex);
            $voterTest = $voter->matchItem($child);

            if ($voterTest == true) {
                $child->setCurrent(true);
            } else {
                $child->setCurrent(false);
            }
        }
    }
```

This is working well but the regexVoter check my regex with childs routes so it become "true" everytime it check and for every childs...

I tried to pass only one child but the voter still returning "true"

```
private function matchingRoute($menu)
    {
       $childName = $menu->getChild('sidebar.front.domains');
       $childRegex = $childName->getAttribute('regex');

       $voter = new RegexVoter($childRegex);
       $voterTest = $voter->matchItem($childName);

        if ($voterTest == true) {
            $childName->setCurrent(true);
        } else {
            $childName->setCurrent(false);
        }
    }
```

How can i this voter check only one child to have the good child with "current" class?
Can the regex check the current route instead of childs routes ?

Thanks.

**Comment by stof** [comment]
I don't understand what you mean. What is this ``matchingRoute`` function ?

And btw, I cannot really help you debug things if I don't know how your item URIs and regex are looking

**Comment by Jerome1337** [comment]
My regex look like that : ```#^/servers/#``` ```#^/domains/#``` ```#^/uptimes/#``` etc...
I have URIs like that : ```/servers/foo/bar``` ```/domains/foo/bar``` ```/uptimes/foo/bar```

My ```matchingRoute``` function is called when the menu is created, this function add ```class: current``` to menu children but all of them like that 

![screen shot 2015-11-30 at 10 27 09](https://cloud.githubusercontent.com/assets/7968649/11468066/fb075d3e-974c-11e5-85a5-36b750fbce71.png)

What i want to have is, only the child ```servers``` for exemple, with ```class: current``` when URIs are like this ```/servers/```, this ```/servers/foo/```  or this ```/servers/foo/bar```

Without my ```matchingRoute``` function this is working for this ```/servers/``` URIs but not for ```/servers/foo/```  or ```/servers/foo/bar```

I hope this will help you to understand my problem.

**Comment by stof** [comment]
I don't understand why you have such ``matchingRoute`` function. You should just register the RegexVoter in the matcher used by the menu renderer

**Comment by Jerome1337** [comment]
Yea, i don't why didn't do that before, this is workign well.
Thank
