### ISSUE TITLE
Symfony routing extension uses deprecated value for $referenceType

### ISSUE THREAD

**Issue by sgilberg** [KnpLabs/KnpMenu#229]
In Knp\Menu\Integration\Symfony\RoutingExtension, there is a call to the generate() method of Symfony's UrlGenerator which uses a deprecated boolean value for its $referenceType parameter (represented here by $absolute):

```
public function buildOptions(array $options = array())
    {
        if (!empty($options['route'])) {
            $params = isset($options['routeParameters']) ? $options['routeParameters'] : array();
            $absolute = isset($options['routeAbsolute']) ? $options['routeAbsolute'] : false;
            $options['uri'] = $this->generator->generate($options['route'], $params, $absolute);

            // adding the item route to the extras under the 'routes' key (for the Silex RouteVoter)
            $options['extras']['routes'][] = array(
                'route' => $options['route'],
                'parameters' => $params,
            );
        }

        return $options;
    }
```
In Symfony 2.8, defaulting to false for the $absolute parameter throws the following deprecation notice: 
"The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead."

This could be resolved by changing false to the appropriate constant, i.e.:
```
 $absolute = isset($options['routeAbsolute']) ? $options['routeAbsolute'] : UrlGeneratorInterface::ABSOLUTE_PATH;
```
But I'm not sure how best to do that and maintain compatibility with Symfony <2.8. Also not sure if maybe a greater change is needed, such as replacing 'routeAbsolute' with 'routeReferenceType' or something like that.

**Comment by stof** [comment]
Fixed in the master branch by #226
