### ISSUE TITLE
MegaMenu

### ISSUE THREAD

**Issue by Audax23** [KnpLabs/KnpMenu#231]
Hi,
I'd like to know how to put some html to make a megamenu with this bundle, i've search full example but no success.
thank you for your answers

**Comment by Nek-** [comment]
If you want to design your menu, please consider using the twig template or create your own renderer class. The main goal of knpmenu is not to render "megamenu" but build them. You can use extra option to specify more information to your template or can create a custom `MenuItem`.

Do not hesitate to read the doc. If you're using Symfony, try the bundle.
