### ISSUE TITLE
Add title to li element

### ISSUE THREAD

**Issue by ansin218** [KnpLabs/KnpMenu#232]
I want to add tooltip for all the menu elements using title attribute. I want to add it in the li tag. 
I found where the li tag in the twig file is but it is not reflecting. What should I do?

**Comment by jonny827** [comment]
@ansin218 According to [Basic Docs here](https://github.com/KnpLabs/KnpMenu/blob/master/doc/01-Basic-Menus.markdown)   you need to take advantage of Menu Attributes. To modify the doc's example based on your requirements see below:

`$menu->addChild('Home', array('attributes' => array('id' => 'back_to_homepage')));
$menu['Home']->setAttribute('title', 'YourToolTip');`
