### ISSUE TITLE
Way to retrieve current voters in Matcher

### ISSUE THREAD

**Issue by ConneXNL** [KnpLabs/KnpMenu#234]
The voters in the Knp\Menu\Matcher\Matcher are currently private and there is no getVoters().

I am trying to update the requests of all the voters, however there is not an easy way to get an traversable object of all the current voters.

Is it an idea to add public getVoters() on the Knp\Menu\Matcher\Matcher?

**Comment by jonny827** [comment]
@ConneXNL  I would suggest creating a Pull Request so the core team is presented with the possibility to merge and a discussion can form around the idea.

**Comment by dbu** [comment]
ping @ConneXNL do you plan to follow up on this one or can we close it?

**Comment by stof** [comment]
I don't like the idea of a class providing getters for its dependencies. The Matcher is not meant to be a service locator for voters. So -1 for adding this method.

**Comment by dbu** [comment]
nothing happened in the last year, lets close it.
