### ISSUE TITLE
Create more than 2-th level 

### ISSUE THREAD

**Issue by mishki-svami** [KnpLabs/KnpMenu#235]
Can I create more than 2-th level of menu (for example admin->settings->users)? Thanks for answer.

**Comment by Kwbmm** [comment]
Did you try this:

    $menu = $app['knp_menu.factory']->createItem('root');
    $menu->addChild('admin', array('uri' => '/admin'));
    $menu['admin']->addChild('settings', array('uri' => '/admin/settings'));
    $menu['admin']['settings']->addChild('users',array('uri'=>'/admin/settings/users'));
    return $menu;

**Comment by stof** [comment]
what @Kwbmm said is working. Note that ``->addChild()`` also returns the Item object for the new child (the one you would also access with ``$menu['admin']``)
