### ISSUE TITLE
Is there an automatic way to add a class to all <li> tags generated by the menu?

### ISSUE THREAD

**Issue by adrianocr** [KnpLabs/KnpMenu#236]
I use the Foundation CSS Framework and for the menu to look correct all the `<li>` tags need to have a `class="menu-text"` attribute. Also, the `<ul>` tags (top level and submenu) need to have a `class="menu vertical"` or `class="menu horizontal"` attribute. Is there a way to add this for all items at once? `->addAttribute` after each and every link works. But what if there are a lot of them? It becomes just as much work as coding the menu by hand. 

Thanks!

**Comment by WouterJ** [comment]
You can override the default template used to render the menu and add the new class. When using twig, you would do something like:
```php
$menuRenderer = new \Knp\Menu\Renderer\TwigRenderer($twig, 'custom_menu.html.twig', $itemMatcher);
```
```jinja
{# custom_menu.html.twig #}
{% extends 'knp_menu.html.twig' %}

{% block list %}
    {% set listAttributes = [listAttributes.class is not empty ? listAttributes.class : '', 'menu horizontal']|join(' ') %}
    {{ parent() }}
{% endblock %}

{% block item %}
    {% set classes = item.attribute('class') is not empty ? [item.attribute('class')] : [] %}
    {% do item.setAttribute('class', classes|merge(['menu-text'])|join(' ')) %}
    {{ parent() }}
{% endblock %}
```

Or when using the list renderer, you would override the `renderItem()` and `renderList()` methods.
