### ISSUE TITLE
Route with integer parameters not matched

### ISSUE THREAD

**Issue by greg0ire** [KnpLabs/KnpMenu#240]
I have a route that is not matched by the RouteVoter, because it is an integer, and the RouteVoter compares something that will always be an integer with something that will always be cast to string. What is the rationale between the string cast : https://github.com/KnpLabs/KnpMenu/blob/master/src/Knp/Menu/Matcher/Voter/RouteVoter.php#L81 ?

**Comment by greg0ire** [comment]
See discussion here : https://github.com/KnpLabs/KnpMenu/pull/128/files/91085b40edc0f099a795837991b1b60f968e4240..43fa7023061ef9bc290c994e55aec02934afd649#r64742292

**Comment by dbu** [comment]
@greg0ire is this still an issue? or is the problem that you passed an integer as route parameter to the menu item? all parameters in the configuration must be string with #128

**Comment by greg0ire** [comment]
I worked around that by creating an `IntegerCompatibleRouteVoter` in my app, so yes, it is still an issue.

**Comment by greg0ire** [comment]
> all parameters in the configuration must be string

Looks like a wrong assumption as per [@stof 's comment](https://github.com/KnpLabs/KnpMenu/pull/128/files/91085b40edc0f099a795837991b1b60f968e4240..43fa7023061ef9bc290c994e55aec02934afd649#r64758337). Anyway, is there a benefit to adding such a cast ?

**Comment by dbu** [comment]
i honestly don't know. to me it seems like a valid use case for `!=`
actually. php is not strictly typed, so why complicate things in this
situation.

**Comment by greg0ire** [comment]
The git log does not show any reason for this cast, so I'd say remove it, wait for people to scream and then recomit it with a good commit message.
