### ISSUE TITLE
Last version is broken ?

### ISSUE THREAD

**Issue by jorismulliez** [KnpLabs/KnpMenu#248]
Hi,

I just open an issue in the repository of KnpMenuBundle : https://github.com/KnpLabs/KnpMenuBundle/issues/330

My Symfony App is broken since I ran a composer update.

I looked into composer.json of KnpMenuBundle and I see the dependency (https://github.com/KnpLabs/KnpMenuBundle/blob/2.1.2/composer.json#L22 ) : 

```
"knplabs/knp-menu": "~2.1",
```

So if I understand the version of KnpMenu should be < 2.2 ?

But when I looked into my general composer.lock I see this line : 

```
        {
            "name": "knplabs/knp-menu",
            "version": "2.2.0",
...
```

Is it the normal ?

Thanks for your help,

**Comment by stephanvierkant** [comment]
What do you mean by 'broken'? Please add an error message.

**Comment by stof** [comment]
``~2.1`` means ``>=2.1,<3.0``. So I don't see any issue here.

**Comment by wouterj** [comment]
Closing as it's waiting for a response for a long time. I also don't see what exactly is broken here.

If you have more information and still think this is broken, please add a new comment. We can always reopen :)
