### ISSUE TITLE
BUG: Unable to find template "knp_menu.html.twig"

### ISSUE THREAD

**Issue by Aerendir** [KnpLabs/KnpMenu#252]
The error appeared after upgrading composer that upgraded Symfony to version 2.8.16.
Falling back to Symfony 2.8.15 "solves" the error.

What have I to do?

[I opened this same issue on the Symfony repository, too.](https://github.com/symfony/symfony/issues/21281)

**Comment by xabbuh** [comment]
This was a bug in Symfony that was fixed in symfony/symfony#21285 and will be part of the next patch releases. As a workaround you have to make sure that TwigBundle is registered before KnpMenuBundle in your application kernel.

**Comment by weaverryan** [comment]
Closing - as issue (thanks to @xabbuh) is already fixed in the core! Just downgrade to the previous patch release, or wait until the next path release (e.g. it will be fixed in 2.8.17, whenever that is released).

**Comment by xabbuh** [comment]
> Just downgrade to the previous patch release, or wait until the next path release (e.g. it will be fixed in 2.8.17, whenever that is released).

Or check the order in which the bundles are registered in the kernel (see https://github.com/KnpLabs/KnpMenu/issues/252#issuecomment-272724258 and https://github.com/symfony/symfony/issues/21281#issuecomment-272578100).
