### ISSUE TITLE
A bug in documentation $itemMatcher = \Knp\Menu\Matcher\Matcher(); missing new

### ISSUE THREAD

**Issue by PeterZhukov** [KnpLabs/KnpMenu#261]
Threre is a bug in documentation: https://github.com/KnpLabs/KnpMenu/blob/master/doc/04-Iterators.md
`$itemMatcher = \Knp\Menu\Matcher\Matcher(); `
should be 
`$itemMatcher = new \Knp\Menu\Matcher\Matcher(); `

**Comment by stof** [comment]
Can you send a pull request fixing the doc ? this way, you would get authorship on the fix.

**Comment by PeterZhukov** [comment]
I'm sorry, I'm a newbie to github workflow, so by now I can't.

**Comment by stof** [comment]
Well, for such a small documentation change, you can do it in the github interface directly (click on the edit button when looking at this file)

**Comment by PeterZhukov** [comment]
Ok, done.
