### ISSUE TITLE
[RFC] Drop support for older PHP versions

### ISSUE THREAD

**Issue by stof** [KnpLabs/KnpMenu#273]
Currently, all KnpMenu packages (the library, the bundle and the silex provider) have PHP 5.3 as their min version (the silex provider will bump to at least 5.5.9 for version 2, as Silex 2 has 5.5.9 as min requirement).
This version is EOLed since a long time, and testing on it becomes harder, as Travis is currently sunsetting the Precise infrastructure, and their Trusty environment does not offer PHP 5.3.
Due to this, I would like to drop support for at least PHP 5.3 in the next minor release (2.3 for the library, 2.2 for the bundle and 1.1 for the Silex provider). The question here is what should the new requirement be:

- 5.5.9, to match the Symfony 3 and Silex 2 requirement
- 5.6 (oldest non-EOLed PHP version currently, but security-only)
- 7.0 (oldest actively supported PHP version currently)
- 7.1 (which will be the min requirement for Symfony 4 btw)

What do you think @dbu @flug ?

**Comment by dbu** [comment]
packagist does not have statistics on what php version users of this lib have, or does it? i would jump to 5.6 and then to 7.1 when symfony 4 is out and we possibly need a new major version anyways. (imo its ok to increase php version in minor release, but unless you actively need some php 7 feature, i'd not rush it. and in a major version change we could e.g. use strict scalar types in all interfaces)

**Comment by stof** [comment]
@dbu I don't think it does

**Comment by dbu** [comment]
so lets do a "soft" jump to 5.6 in a minor version, and then possibly a larger refactoring for symfony 4 using all the php 7 goodness?
