### ISSUE TITLE
Obsolete docs for tree menu

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpMenu#277]
The [tree menu](https://github.com/KnpLabs/KnpMenu/blob/a74c02bbc892aba64d05ff0098f00a6d1b601892/doc/01-Basic-Menus.markdown#creating-a-menu-from-a-tree-structure) doc is out of date.
It's still mentioning `createFromNode` mehtod, that is gone in the `2.0.0` version.

I managed to get a version working with `NodeLoader`, but I'm not sure if I'm using it in the proper way, so I can't do a PR to correct the doc since I don't know how to properly replace the legacy code.
If someone points me in the right direction, I'll be glad to open a PR.

This is how I'm doing now:
```php

<?php

namespace App\Menu;

use Knp\Menu\FactoryInterface;
use Knp\Menu\ItemInterface;
use Knp\Menu\Loader\NodeLoader;

class Builder
{
    private $factory;

    public function __construct(FactoryInterface $factory)
    {   
        $this->factory = $factory;
    }   

    public function createMenu(): ItemInterface
    {   
        $loader = new NodeLoader($this->factory);
        $rootNode = /* ... get an object implementing \Knp\Menu\NodeInterface */;
        $menu = $loader->load($rooNode);

        return $menu;
    } 
}
```

**Comment by stof** [comment]
You are indeed using it the right way. Can you send a doc PR ? I would even make it a separate chapter rather than having it in the basic doc (this is not basic usage of the lib)

**Comment by malutanpetronel** [comment]
How should the service part look please ?
