### ISSUE TITLE
Not passing a RequestStack as the first argument for "Knp\Menu\Matcher\Voter\RouteVoter"

### ISSUE THREAD

**Issue by ickbinhier** [KnpLabs/KnpMenu#282]
User Deprecated: Not passing a RequestStack as the first argument for "Knp\Menu\Matcher\Voter\RouteVoter" constructor is deprecated since version 2.3 and won't be possible in 3.0.

**Comment by ickbinhier** [comment]
the same Problem???

User Deprecated: The Knp\Menu\Matcher\Voter\RouteVoter::setRequest() method is deprecated since version 2.3 and will be removed in 3.0. Pass a RequestStack in the constructor instead.

and

User Deprecated: The Knp\Menu\Matcher\Matcher::addVoter() method is deprecated since version 2.3 and will be removed in 3.0. Pass voters in the constructor instead.

**Comment by stof** [comment]
If you are using KnpMenuBundle, you need to update it to the latest version.

**Comment by ickbinhier** [comment]
oh sorry....
