### ISSUE TITLE
Need more documentation :3

### ISSUE THREAD

**Issue by denvolj** [KnpLabs/KnpMenu#288]
Need more information about MenuItem, "extras" and it's defaults. 

For example ([doc](https://github.com/KnpLabs/KnpMenu/blob/master/doc/01-Basic-Menus.markdown#customizing-each-menu-item)):
I even didn't know about "safe_label" and spend ~30 minutes to solve problems with item render.

P.S> sorry for my bad english.

**Comment by Nek-** [comment]
As I see, this is documented:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/972456/38369749-ba2ebc68-38e8-11e8-975e-26e0c423c261.png">

Feel free to contribute in order to make this documentation better.

**Comment by tricoos** [comment]
3 years later and I also stumbled into this - this is where the documentation and code can be improved:
- rename "safe_label" to "is_safe_label" to avoid confusion (you don't have to specify any label but the boolean value!)
- add an example for any "extras" setting right there, actually an example for simply using HTML code inside a menu entry.

For everyone also stumbling on this:
```
$factory = new MenuFactory();
$menu    = $factory->createItem();

$menu->addChild('Link title', ['uri' => '/example', 'extras' => ['safe_label' => true ]]); 
...
$renderer = new ListRenderer(new Matcher());
echo $renderer->render($menu, ['allow_safe_labels' => true]);
```
