### ISSUE TITLE
Adding a maintainer

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpMenu#303]
I see that this repo has, unfortunately, a very low activity: only 7 commits in 2019, no releases since 2017, many PRs stuck event if very simple.
So, I'm offering my help as maintainer of this repo.
For references, I'm already helping in maintenance of KnpComponents and KnpPaginatorBundle, I'm lead maintainer in VichUploaderBundle, and I also maintain some small packages in [BeeLab organization](https://github.com/bee-lab/).
WDYT @stof?

**Comment by derrabus** [comment]
Related: https://knplabs.com/en/blog/news-for-our-foss-projects-maintenance

Since I use this library myself often, I'd also offer my help with maintaining this library and the corresponding bundle.
