### ISSUE TITLE
Drop support for php < 7.2

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpMenu#305]
I think we should increase requirements to support only php 7.2 and newer.
Some points for a such move:
* older php versions are [out of support](https://www.php.net/supported-versions.php)
* we already did the same move a couple of years ago in bf110b784c04311afc1e30684b434e13ca1e6b4e
* [related Symfony bundle](https://github.com/KnpLabs/KnpMenuBundle) has already increased requirements
* users of older php versions will be still supported, via older library versions
* pushing the ecosystem

**Comment by derrabus** [comment]
This would also allow us to modernize public interfaces by adding type-hints.
