### ISSUE TITLE
What is the reason of having two tags for 2.2.0 version of a library?

### ISSUE THREAD

**Issue by anyt** [KnpLabs/KnpMenu#315]
When running composer update we've got an error related to conflict of `knplabs/knp-menu` and `twig`. But version constraints for these packages in composer haven't changed for a long time and it worked before.
I guess it's related to the fact that there is a new tag https://github.com/KnpLabs/KnpMenu/releases/tag/v2.2.0 tagged this on Sep 2.
However there also https://github.com/KnpLabs/KnpMenu/releases/tag/2.2.0 released this on Sep 22, 2016.

So probably before we used an old tag without error as composer.json hadn't defined the conflict with twig.
Could you explain is it an error or done intentionally and how should we work with that.

Thank you.

**Comment by garak** [comment]
v2.2.0 was a mistake. Is deleted now

**Comment by Grygir** [comment]
Looks like tag **v2.2.0** still exists https://github.com/KnpLabs/KnpMenu/releases/tag/v2.2.0
and that mistaken version is distributed over packagist https://packagist.org/packages/knplabs/knp-menu#v2.2.0

But not **2.2.0**, that suppose to be correct one https://github.com/KnpLabs/KnpMenu/releases/tag/2.2.0

**Comment by garak** [comment]
That's weird.
Anyway, I re-deleted tag v2.2.0

**Comment by anyt** [comment]
The issue appeared again. Can you drop the extra tag one more time and review your release workflow to not do publish it again? 
thank you!

**Comment by wouterj** [comment]
Probably a maintainer still has the tag locally and pushes without specifying the branch? Then, git will automatically push any tag that is not yet known on the remote IIRC

**Comment by garak** [comment]
Re-deleted tag. Tomorrow I'll check local tags on my computer

**Comment by anyt** [comment]
v2.2.0 tag added back again...
https://github.com/KnpLabs/KnpMenu/releases/tag/v2.2.0
Please remove the tag from the github, as it blocks the composer update for the projects, using this version of the library.

**Comment by stof** [comment]
I deleted the tag again. But the hard part about that is that to prevent it from being pushed again, all maintainers have to make sure they also delete it locally (deleting tags fully is a pain, by design of tags)

**Comment by stof** [comment]
And if they fetch from a fork which contains this broken tag, it will recreate it locally too
