### ISSUE TITLE
Allow Twig 3

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpMenu#319]
Twig 3 has been released a few days ago, we should add support for it

**Comment by garak** [comment]
I'm trying to find a solution, but I'm stuck with errors `MenuExtensionTest`.
Our [current implementation](https://github.com/KnpLabs/KnpMenu/blob/master/tests/Knp/Menu/Tests/Twig/MenuExtensionTest.php#L192) is calling directly `loadTemplate` method of `Twig\Environment` class, but it looks like such method is kind of internal and not meant to be called from outside. So, method signature is changed in Twig 3 and I don't know how to handle this.

I tried a possible solution: adding a `TwigTestTemplate` class that extends `Twig\Template` and doing:

```php
return Environment::MAJOR_VERSION < 3 ? 
            $twig->loadTemplate('index') : 
            $twig->loadTemplate(TwigTestTemplate::class, 'index' $index);
```

in the last line of our 'getTemplate` method.
It doesn't work. 
 I get an exception:

>Twig\Error\RuntimeError: Failed to load Twig template "index", index "": cache might be corrupted in "index"

**Comment by garak** [comment]
@stof do you have any suggestions?

**Comment by DonCallisto** [comment]
@garak I suppose you should use [load](https://github.com/twigphp/Twig/blob/6b2e6e6d05a7511c2cac4636b5e3179b110622c1/src/Environment.php#L303) function and not `loadTemplate` then call `unwrap` or use directly `TemplateWrapper` (didn't check where `getTemplate` of this library is used)
