### ISSUE TITLE
LazyProvider must be compatible with ...

### ISSUE THREAD

**Issue by pdias** [KnpLabs/KnpMenu#321]
I think there is a problem in the following classes (LazyProvider, ArrayAccessProvider and PsrProvider) in the method **"has"**.

`php.CRITICAL: 
Fatal Compile Error: 
Declaration of Knp\Menu\Provider\LazyProvider::has($name, array $options = Array): bool must be compatible with Knp\Menu\Provider\MenuProviderInterface::has(string $name, array $options = Array): bool {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Declaration of Knp\\Menu\\Provider\\LazyProvider::has($name, array $options = Array): bool must be compatible with Knp\\Menu\\Provider\\MenuProviderInterface::has(string $name, array $options = Array): bool at /home/my/vendor/knplabs/knp-menu/src/Knp/Menu/Provider/LazyProvider.php:14)"}`

**The method declarion is:**

`public function has($name, array $options = []): bool`

**And it must be:**

`public function has(string $name, array $options = []): bool`

**Comment by stof** [comment]
which version are you using ?

**Comment by pdias** [comment]
I'm using Sf 3.4.36, knplabs/knp-menu:dev-master with php - 7.2.24 on CentOS.

**Comment by stof** [comment]
hmm, https://github.com/KnpLabs/KnpMenu/pull/306 indeed has a bug where some `add` methods died not receive the typehint `LazyProvider`, but also `PsrProvider`). Would you mind sending a PR for that ?

**Comment by stof** [comment]
Fixed in #324
