### ISSUE TITLE
Using pattern and route together

### ISSUE THREAD

**Issue by Clindbergh** [KnpLabs/KnpMenu#329]
When defining an item I'm trying to use `route` and `pattern` together in the sense as described here: https://github.com/KnpLabs/KnpMenuBundle/issues/155#issuecomment-51617769

However whenever a `route` is set, a `pattern` will be ignored. It would be expected, that the pattern is used to test for a match, when the route did not match.

```php
    $menu->addChild('Item', [
        'route' => 'my_route', 
        'extras' => [
            'routes' => [ 'pattern' => 'my_route.*']
         ]
     ]);
```

**Comment by stof** [comment]
Your patter is not a valid regexp.

**Comment by Clindbergh** [comment]
What is wrong with the regexp?

However I think the issue persists.

**Comment by Clindbergh** [comment]
When building the item as described above, `\Knp\Menu\Integration\Symfony\RoutingExtension::buildOptions` will add the `route` to the extras item. 

The issue is in the following code in `\Knp\Menu\Matcher\Voter\RouteVoter::matchItem`:

```php
       $routes = (array) $item->getExtra('routes', []);
// $routes is now [ pattern="my_route.*", 0 = [ route = "my_route", parameters= []]

        foreach ($routes as $testedRoute) {
// in the first iteration, $testedRoute is "my_reoute.*"
            if (\is_string($testedRoute)) {
// this will be true in the first iteration, thus the pattern 
// will be passed to isMatchingRoute as a route
                $testedRoute = ['route' => $testedRoute];
            }

            if (!\is_array($testedRoute)) {
                throw new \InvalidArgumentException('Routes extra items must be strings or arrays.');
            }

            if ($this->isMatchingRoute($request, $testedRoute)) {
                return true;
            }
        }
```
Subsequently in \Knp\Menu\Matcher\Voter\RouteVoter::isMatchingRoute` the pattern is never tested because `$testedRoute['route']` is always set.

```php 
    private function isMatchingRoute(Request $request, array $testedRoute): bool
    {
        $route = $request->attributes->get('_route');
        if (isset($testedRoute['route'])) {
            if ($route !== $testedRoute['route']) {
                return false;
            }
        } elseif (!empty($testedRoute['pattern'])) {
            if (!\preg_match($testedRoute['pattern'], $route)) {
                return false;
            }
```

**Comment by Clindbergh** [comment]
Above pull request will make a menu item with a pattern functional as below functional again:

**Comment by stof** [comment]
Ah no, I found the issue. `routes` takes a *list* of routes to match, which can be either a string (for the shortcut case) or an associative array. Your config misses a level of array.

**Comment by stof** [comment]
Compare your config with the the example you linked in the description.

**Comment by Clindbergh** [comment]
Thanks 👍 , didn't spot that. This works now.
