### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by vladyslavstartsev** [KnpLabs/KnpMenu#338]
There is no PHP5 support in this lib.

![image](https://user-images.githubusercontent.com/17382248/100553507-ea297200-3296-11eb-8f52-e8a08fb4bac9.png)

**Comment by vladyslavstartsev** [comment]
Also in `README` you can see `The KnpMenu library provides object oriented menus for PHP 7.`

But in `composer.json` you can see support for PHP 7 and 8

**Comment by derrabus** [comment]
Thanks for merging, @garak. Can you please also update the project description on GitHub?

**Comment by garak** [comment]
> Thanks for merging, @garak. Can you please also update the project description on GitHub?

Unfortunately, I can't.

**Comment by stof** [comment]
done
