### ISSUE TITLE
Drop support for PHP 7.3?

### ISSUE THREAD

**Issue by stephanvierkant** [KnpLabs/KnpMenu#357]
I see this library still supports PHP 7.3, which is End of Life (EOL) as of today. What's the policy about PHP support? The only [supported versions](https://www.php.net/supported-versions.php) are 7.4, 8.0 and 8.1.

In my opinion libraries should drop support of PHP versions that are end of life, because it makes contributing to this library much easier.

**Comment by wouterj** [comment]
> In my opinion libraries should drop support of PHP versions that are end of life, because it makes contributing to this library much easier.

I'm not sure about the policies of this bundle, but I'm wondering which 7.4 feature would make it easier to contribute? I'm generally not sure about bumping minimum requirements for the sake of doing just that, but things change if there is actually a real advantage.

**Comment by stephanvierkant** [comment]
I can name some new features, but I'm sure you know them as well (and maybe even better ;)). Personally speaking, I like the typed properties and the arrow functions. But you're right when you say there is no need to use those features right now. 

But generally speaking, it's easier to contribute when you can use 'new' (they're not new anymore, are they?) features and I think more open source projects should have a clear policy about how and when to drop support for a EOL-version of PHP. Currently, some say dropping support is a BC, others don't. Some are dropping support right away, some are still supporting 5.6 (!).

**Comment by garak** [comment]
@stephanvierkant can you please go ahead and propose a pull request?
