### ISSUE TITLE
Change \Knp\Menu\MenuFactory::getExtension to protected instead of private!

### ISSUE THREAD

**Issue by magdicom** [KnpLabs/KnpMenu#359]
Using PHP 8.0

trying to extend `\Knp\Menu\MenuFactory`  to alter the `createItem` method (was trying to replace "MenuItem" with another class), the following error is given:

> Call to private method Knp\Menu\MenuFactory::getExtensions() from scope "Foo\Bar\BazFactory"

is there a better way to specify the desired "MenuItem" class instead of replicate the whole class of "MenuFactory"?

**Comment by magdicom** [comment]
#360 
#361

**Comment by garak** [comment]
I'm not sure that making class extensible could be good. Indeed, the class should be final (we can't make it final for now just to keep BC).

**Comment by magdicom** [comment]
> I'm not sure that making class extensible could be good. Indeed, the class should be final (we can't make it final for now just to keep BC).

with the amount of classes I've written in the past two days I really think it would be better if I clone this rep. and do whatever needed!

**Comment by garak** [comment]
> > I'm not sure that making class extensible could be good. Indeed, the class should be final (we can't make it final for now just to keep BC).
> 
> with the amount of classes I've written in the past two days I really think it would be better if I clone this rep. and do whatever needed!

If you think that copying an entire repository is better than copying a couple of classes, you're free to do so.
