### ISSUE TITLE
Matcher::addVoter() method undefined

### ISSUE THREAD

**Issue by magdicom** [KnpLabs/KnpMenu#362]
following the documentation [here](https://github.com/KnpLabs/KnpMenu/blob/master/doc/05-Matcher.md)

it gives an error `addVoter` does not exist.

**Comment by garak** [comment]
You're right, the voter should be added to the constructor.
Can you propose a PR?

**Comment by magdicom** [comment]
#363

**Comment by garak** [comment]
Sorry for the misunderstanding: the PR should change the documentation, not the code
