### ISSUE TITLE
What about PHP8.1 support?

### ISSUE THREAD

**Issue by palansher** [KnpLabs/KnpMenu#371]
Hello!

Do you plan to change

"require": {
        "php": "^7.3 || ^8.0",
to

        "php": "^7.4 || ^8.1",
?

Thanks for your efforts !

**Comment by garak** [comment]
No, we don't plan to make that change at the moment.
The change would only drop support for PHP 8.0, which would make no sense (unless we drop 7.4 as well)
PHP 8.1 is already supported, as you can see in our Actions

**Comment by stof** [comment]
The change you are requesting would not add any support for PHP 8.1 (which is already there). It would only **remove** support for PHP 8.0. So it does not make sense (and it is not planned for now)
