### ISSUE TITLE
getting the actual label, not the label ?? name

### ISSUE THREAD

**Issue by tacman** [KnpLabs/KnpMenu#388]
in MenuItem.php

```php

    /**
     * Returns the label that will be used to render this menu item
     *
     * Defaults to the name of no label was specified
     */

    public function getLabel(): string
    {
        return $this->label ?? $this->name;
    }
```

Sometimes I have an icon only, or a decoration like a divider, and I've explicitly set the label to empty.  I'd like a way to get the actual label, not the label or name.  I need the name because that's the id, I don't want to not set an id because I want an empty label.

Any suggestions?  I guess something like getRawLabel(): ?string, but I'm not sure about that solution.

**Comment by stof** [comment]
Set the label to an empty string, and this will return an empty string. The fallback is done only when `$this->label` is `null`

**Comment by tacman** [comment]
Ah, thanks!
